settings:
  tg:
    enable: false
    token: ""
    ids:
      - 0
  vk:
    enable: false
    token: ""
    ids:
      - 0
  time:
    format: "HH:mm:ss dd-MM-YYYY"

messages:
  none-player: "неизвестно"
  none-time: "бессрочно"
  ban:
    - "Игрок был наказан"
    - " "
    - "Нарушитель: %player%"
    - "Выдано: %time%"
    - "Действует до: %time_end%"
    - "Причина: %reason%"
    - "Тип наказания: %type%"
    - "На сервере: %server%, действует на %servers%"
    - "Скрыто: %isSilent%"
    - "По IP: %isIp%"
    - "Выдал наказание: %exec_player%"
  mute:
    - "Игрок был наказан"
    - " "
    - "Нарушитель: %player%"
    - "Выдано: %time%"
    - "Действует до: %time_end%"
    - "Причина: %reason%"
    - "Тип наказания: %type%"
    - "На сервере: %server%, действует на %servers%"
    - "Скрыто: %isSilent%"
    - "По IP: %isIp%"
    - "Выдал наказание: %exec_player%"
  warn:
    - "Игрок был наказан"
    - " "
    - "Нарушитель: %player%"
    - "Выдано: %time%"
    - "Действует до: %time_end%"
    - "Причина: %reason%"
    - "Тип наказания: %type%"
    - "На сервере: %server%, действует на %servers%"
    - "Скрыто: %isSilent%"
    - "По IP: %isIp%"
    - "Выдал наказание: %exec_player%"
  kick:
    - "Игрок был наказан"
    - " "
    - "Нарушитель: %player%"
    - "Выдано: %time%"
    - "Действует до: %time_end%"
    - "Причина: %reason%"
    - "Тип наказания: %type%"
    - "На сервере: %server%, действует на %servers%"
    - "Скрыто: %isSilent%"
    - "По IP: %isIp%"
    - "Выдал наказание: %exec_player%"
  unmute:
    - "У игрока сняли нарушение"
    - " "
    - "Нарушитель: %player%"
    - "Выдано: %time%"
    - "Действует до: %time_end%"
    - "Причина: %reason%"
    - "Тип наказания: %type%"
    - "На сервере: %server%, действует на %servers%"
    - "Скрыто: %isSilent%"
    - "По IP: %isIp%"
    - "Выдал наказание: %exec_player%"
  unban:
    - "У игрока сняли нарушение"
    - " "
    - "Нарушитель: %player%"
    - "Выдано: %time%"
    - "Действует до: %time_end%"
    - "Причина: %reason%"
    - "Тип наказания: %type%"
    - "На сервере: %server%, действует на %servers%"
    - "Скрыто: %isSilent%"
    - "По IP: %isIp%"
    - "Выдал наказание: %exec_player%"
  unwarn:
    - "У игрока сняли нарушение"
    - " "
    - "Нарушитель: %player%"
    - "Выдано: %time%"
    - "Действует до: %time_end%"
    - "Причина: %reason%"
    - "Тип наказания: %type%"
    - "На сервере: %server%, действует на %servers%"
    - "Скрыто: %isSilent%"
    - "По IP: %isIp%"
    - "Выдал наказание: %exec_player%"